controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


home:
    path: /
    controller: App\Controller\IndexController::index

connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index

etudiant:
    path: /etudiant
    controller: App\Controller\EtudiantController::index

tache:
    path: /tache
    controller: App\Controller\TacheController::index
