controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index

connexion_process_form:
    path: /connexion-process-form
    controller: App\Controller\ConnexionController::processForm

etudiant:
    path: /etudiant
    controller: App\Controller\EtudiantController::index

tache:
    path: /tache
    controller: App\Controller\TacheController::index
